name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', './package.json') }}
        id: cache

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Test
        run: npm test -- --ci --colors
